PROGS=PrimitiveNonBlk.omp.test      \
      MultiPrimitiveNonBlk.omp.test \
      CollectiveNonBlk.omp.test


# Compilers
CLANGCXX ?= clang++
MPICXX ?= mpicxx

# MPI Wrappers
CXX_WRAPPERS=I_MPI_CXX=$(CLANGCXX) MPICH_CXX=$(CLANGCXX) OMPI_CXX=$(CLANGCXX)

CPPFLAGS=-I.
CFLAGS=-fopenmp -O3 -std=c++11 --gcc-toolchain=$(which gcc | sed 's,/bin/gcc$,,')

ifdef LARGE_INPUT
CPPFLAGS+=-DLARGE_INPUT
endif

# TAMPI Flags
ifndef TAMPI_INCLUDE_PATH
ifndef TAMPI_HOME
$(error TAMPI_HOME must be defined if TAMPI_INCLUDE_PATH is not)
endif
TAMPI_INCLUDE_PATH=$(TAMPI_HOME)/include
endif

ifndef TAMPI_LIBRARY_PATH
ifndef TAMPI_HOME
$(error TAMPI_HOME must be defined if TAMPI_LIBRARY_PATH is not)
endif
TAMPI_LIBRARY_PATH=$(TAMPI_HOME)/lib
endif

TAMPI_CPPFLAGS=-I$(TAMPI_INCLUDE_PATH)
TAMPI_LDCFLAGS=-L$(TAMPI_LIBRARY_PATH) -ltampi-c

all: $(PROGS)

%.omp.test: omp/%.cpp
	@echo "  MPICXX $@"
	$(CXX_WRAPPERS) $(MPICXX) $(CPPFLAGS) $(CFLAGS) $(TAMPI_CPPFLAGS) $^ -o $@ $(TAMPI_LDCFLAGS)

clean:
	rm -f *.o *.test *.mod
