PROGS=DoNotExecute.ompss2.test         \
      DoNotExecutef.ompss2.test        \
      PrimitiveBlk.ompss2.test         \
      PrimitiveNonBlk.ompss2.test      \
      PrimitiveWrappers.ompss2.test    \
      MultiPrimitiveBlk.ompss2.test    \
      MultiPrimitiveNonBlk.ompss2.test \
      CollectiveBlk.ompss2.test        \
      CollectiveNonBlk.ompss2.test     \
      HugeBlkTasks.ompss2.test         \
      HugeTasks.ompss2.test

# Compilers
CXX=g++
MCXX=mcxx
MF90=mfc
MPICXX=mpicxx
MPIF90=mpif90

# Special case for Intel MPI
ifdef I_MPI_ROOT
CXX=g++
MCXX=mcxx
MF90=mfc
MPICXX=mpiicpc
MPIF90=mpiifort
endif

# MPI Wrappers
CXX_WRAPPERS=I_MPI_CXX=$(MCXX) MPICH_CXX=$(MCXX) OMPI_CXX=$(MCXX)
F90_WRAPPERS=I_MPI_F90=$(MF90) MPICH_FC=$(MF90) OMPI_FC=$(MF90)

CPPFLAGS=-I.
CFLAGS=--ompss-2 -O3 -std=c++11
FFLAGS=--ompss-2 -O3 --pp

TAMPI_CPPFLAGS=-I$(TAMPI_HOME)/include
TAMPI_LDFLAGS=-L$(TAMPI_HOME)/lib -L$(TAMPI_HOME)/lib64 -l:libtampi.a -lstdc++

all: $(PROGS)

%.ompss2.test: ompss2/%.cpp
	$(CXX_WRAPPERS) $(MPICXX) $(CPPFLAGS) $(CFLAGS) $(TAMPI_CPPFLAGS) $^ -o $@ $(TAMPI_LDFLAGS)

%.ompss2.test: ompss2/%.F90
	$(F90_WRAPPERS) $(MPIF90) $(CPPFLAGS) $(FFLAGS) $(TAMPI_CPPFLAGS) $^ -o $@ $(TAMPI_LDFLAGS)

clean:
	rm -f *.o *.test *.mod
