PROGS=DoNotExecute.ompss2.test         \
      DoNotExecutef.ompss2.test        \
      PrimitiveBlk.ompss2.test         \
      PrimitiveNonBlk.ompss2.test      \
      PrimitiveWrappers.ompss2.test    \
      MultiPrimitiveBlk.ompss2.test    \
      MultiPrimitiveNonBlk.ompss2.test \
      CollectiveBlk.ompss2.test        \
      CollectiveNonBlk.ompss2.test     \
      HugeBlkTasks.ompss2.test         \
      HugeTasks.ompss2.test

# Compilers
CXX ?= g++
MCXX ?= mcxx
MF90 ?= mfc
MPICXX ?= mpicxx
MPIF90 ?= mpif90

# MPI Wrappers
CXX_WRAPPERS=I_MPI_CXX=$(MCXX) MPICH_CXX=$(MCXX) OMPI_CXX=$(MCXX)
F90_WRAPPERS=I_MPI_F90=$(MF90) MPICH_FC=$(MF90) OMPI_FC=$(MF90)

CPPFLAGS=-I.
CFLAGS=--ompss-2 -O3 -std=c++11
FFLAGS=--ompss-2 -O3 --pp

ifdef LARGE_INPUT
CPPFLAGS+=-DLARGE_INPUT
endif

# TAMPI Flags
ifndef TAMPI_INCLUDE_PATH
ifndef TAMPI_HOME
$(error TAMPI_HOME must be defined if TAMPI_INCLUDE_PATH is not)
endif
TAMPI_INCLUDE_PATH=$(TAMPI_HOME)/include
endif

ifndef TAMPI_LIBRARY_PATH
ifndef TAMPI_HOME
$(error TAMPI_HOME must be defined if TAMPI_LIBRARY_PATH is not)
endif
TAMPI_LIBRARY_PATH=$(TAMPI_HOME)/lib
endif

TAMPI_CPPFLAGS=-I$(TAMPI_INCLUDE_PATH)
TAMPI_LDCFLAGS=-L$(TAMPI_LIBRARY_PATH) -ltampi-c
TAMPI_LDFFLAGS=-L$(TAMPI_LIBRARY_PATH) -ltampi-fortran

all: $(PROGS)

%.ompss2.test: ompss2/%.cpp
	@echo "  MPICXX $@"
	$(CXX_WRAPPERS) $(MPICXX) $(CPPFLAGS) $(CFLAGS) $(TAMPI_CPPFLAGS) $^ -o $@ $(TAMPI_LDCFLAGS)

%.ompss2.test: ompss2/%.F90
	@echo "  MPIF90 $@"
	$(F90_WRAPPERS) $(MPIF90) $(CPPFLAGS) $(FFLAGS) $(TAMPI_CPPFLAGS) $^ -o $@ $(TAMPI_LDFFLAGS)

clean:
	rm -f *.o *.test *.mod
