PROGS=PrimitiveNonBlk.omp.test      \
      MultiPrimitiveNonBlk.omp.test \
      CollectiveNonBlk.omp.test

# Compilers
CXX ?= g++
MPICXX ?= mpicxx

CPPFLAGS=-I.
CFLAGS=-fopenmp -std=c++11 -O3

ifdef LARGE_INPUT
CPPFLAGS+=-DLARGE_INPUT
endif

# TAMPI Flags
ifndef TAMPI_INCLUDE_PATH
ifndef TAMPI_HOME
$(error TAMPI_HOME must be defined if TAMPI_INCLUDE_PATH is not)
endif
TAMPI_INCLUDE_PATH=$(TAMPI_HOME)/include
endif

ifndef TAMPI_LIBRARY_PATH
ifndef TAMPI_HOME
$(error TAMPI_HOME must be defined if TAMPI_LIBRARY_PATH is not)
endif
TAMPI_LIBRARY_PATH=$(TAMPI_HOME)/lib
endif

TAMPI_CPPFLAGS=-I$(TAMPI_INCLUDE_PATH)
TAMPI_LDFLAGS=-L$(TAMPI_LIBRARY_PATH) -l:libtampi.a -lstdc++

all: $(PROGS)

%.omp.test: omp/%.cpp
	@echo "  MPICXX $@"
	$(MPICXX) $(CPPFLAGS) $(CFLAGS) $(TAMPI_CPPFLAGS) $^ -o $@ $(TAMPI_LDFLAGS)

clean:
	rm -f *.o *.test
